#!/usr/bin/env bash
set -e
set -x

. versions

DISTRO=$(lsb_release -i -s)
RELEASE=$(lsb_release -r -s)

if [[ -z "${DISTRO}" || -z "${RELEASE}" ]] ; then
  printf "Unable to determine distro\n"
  exit 1
fi


if [[ "$(id -u)" != "0" ]] ; then
  printf "Run this script as root\n"
  exit 1
fi

APT_UPDATE_CMD="apt-get update"
APT_INSTALL_CMD="apt-get install -y"

if [[ "${DISTRO}" = "Ubuntu" || "${DISTRO}" = "Debian" ]] ; then
  UPDATE_CMD="${APT_UPDATE_CMD}"
  INSTALL_CMD="${APT_INSTALL_CMD}"
  PACKAGE_LIST="libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make build-essential unzip curl git patch"
fi

if [[ -z "${INSTALL_CMD}" ]] ; then
  printf "${DISTRO} ${RELEASE} is not supported - please open an issue\n"
  exit 1
fi

${UPDATE_CMD}
${INSTALL_CMD} ${PACKAGE_LIST}

if [[ ! -d "/src" ]] ; then
  mkdir "/src"
fi

if [[ ! -d "/opt" ]] ; then
  mkdir "/opt"
fi

if [[ ! -f /src/openresty-${OPENRESTY_VERSION}.tar.gz ]] ; then
  curl -R -L -o /src/openresty-${OPENRESTY_VERSION}.tar.gz \
    "https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz"
fi

if [[ ! -f /src/luarocks-${LUAROCKS_VERSION}.tar.gz ]] ; then
  curl -R -L -o /src/luarocks-${LUAROCKS_VERSION}.tar.gz \
    "https://luarocks.github.io/luarocks/releases/luarocks-${LUAROCKS_VERSION}.tar.gz"
fi

if [[ ! -f /src/lua-${LUA_VERSION}.tar.gz ]] ; then
  curl -R -L -o /src/lua-${LUA_VERSION}.tar.gz \
    "https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz"
fi

if [[ ! -d /src/openresty-${OPENRESTY_VERSION} ]] ; then
  tar xf "/src/openresty-${OPENRESTY_VERSION}.tar.gz" -C /src
fi

if [[ ! -d /src/luarocks-${LUAROCKS_VERSION} ]] ; then
  tar xf "/src/luarocks-${LUAROCKS_VERSION}.tar.gz" -C /src
fi

if [[ ! -d /src/lua-${LUA_VERSION} ]] ; then
  tar xf "/src/lua-${LUA_VERSION}.tar.gz" -C /src
  pushd /src/lua-${LUA_VERSION}
  patch -p1 << 'EOF'
diff --git a/src/Makefile b/src/Makefile
index e0d4c9f..27d0fb6 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -8,7 +8,8 @@
 PLAT= none
 
 CC= gcc
-CFLAGS= -O2 -Wall $(MYCFLAGS)
+CFLAGS ?= -O2 -Wall
+CFLAGS += $(MYCFLAGS)
 AR= ar rcu
 RANLIB= ranlib
 RM= rm -f
@@ -23,6 +24,7 @@ MYLIBS=
 PLATS= aix ansi bsd freebsd generic linux macosx mingw posix solaris
 
 LUA_A=	liblua.a
+LUA_SO= liblua.so
 CORE_O=	lapi.o lcode.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o \
 	lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o  \
 	lundump.o lvm.o lzio.o
@@ -36,7 +38,7 @@ LUAC_T=	luac
 LUAC_O=	luac.o print.o
 
 ALL_O= $(CORE_O) $(LIB_O) $(LUA_O) $(LUAC_O)
-ALL_T= $(LUA_A) $(LUA_T) $(LUAC_T)
+ALL_T= $(LUA_A) $(LUA_SO) $(LUA_T) $(LUAC_T)
 ALL_A= $(LUA_A)
 
 default: $(PLAT)
@@ -51,6 +53,9 @@ $(LUA_A): $(CORE_O) $(LIB_O)
 	$(AR) $@ $(CORE_O) $(LIB_O)	# DLL needs all object files
 	$(RANLIB) $@
 
+$(LUA_SO): $(CORE_O) $(LIB_O)
+	$(CC) -shared -o $(LUA_SO) $(CORE_O) $(LIB_O) -lm -ldl
+
 $(LUA_T): $(LUA_O) $(LUA_A)
 	$(CC) -o $@ $(MYLDFLAGS) $(LUA_O) $(LUA_A) $(LIBS)
 
EOF
  popd
fi

if [[ ! -d "/opt/openresty-${OPENRESTY_VERSION}" ]] ; then
  pushd /src/openresty-${OPENRESTY_VERSION}
  ./configure \
    --prefix=/opt/openresty-${OPENRESTY_VERSION} \
    --with-pcre-jit \
    --with-ipv6
  make
  make install
  popd
fi

rm -f /opt/openresty
pushd /opt
ln -s openresty-${OPENRESTY_VERSION} openresty
popd

if [[ ! -f "/opt/openresty-${OPENRESTY_VERSION}/luajit/bin/lua" ]] ; then
  pushd /src/lua-${LUA_VERSION}
  if [[ ! -f "src/luaconf.h.orig" ]] ; then
    mv src/luaconf.h src/luaconf.h.orig
  fi
  sed -e "s,/usr/local,/opt/openresty-${OPENRESTY_VERSION}/luajit,g" < src/luaconf.h.orig > src/luaconf.h
  make TO_LIB="liblua.a liblua.so" clean
  make CFLAGS="-fPIC -O2 -Wall -DLUA_USE_LINUX" linux
  make INSTALL_TOP="/opt/openresty-${OPENRESTY_VERSION}/luajit" TO_LIB="liblua.a liblua.so" install
  popd
fi

if [[ ! -f "/opt/openresty-${OPENRESTY_VERSION}/luajit/bin/luarocks" ]] ; then
  pushd /src/luarocks-${LUAROCKS_VERSION}
  ./configure \
    --prefix=/opt/openresty-${OPENRESTY_VERSION}/luajit \
    --with-lua=/opt/openresty-${OPENRESTY_VERSION}/luajit
  make build
  make install
  popd
fi

if [[ "${DISTRO}" = "Ubuntu" || "${DISTRO}" = "Debian" ]] ; then
  update-alternatives \
    --install /usr/bin/lua lua-interpreter /opt/openresty/luajit/bin/lua 500
  update-alternatives \
    --install /usr/bin/luac lua-compiler /opt/openresty/luajit/bin/luac 500
fi
ln -s /opt/openresty/luajit/bin/luajit   /usr/local/bin/luajit-resty
ln -s /opt/openresty/luajit/bin/luarocks /usr/local/bin/luarocks-resty
ln -s /opt/openresty/bin/resty     /usr/local/bin/resty
ln -s /opt/openresty/bin/openresty /usr/local/bin/openresty
