#!/bin/sh

OPENRESTY_VERSION="1.19.3.1"
LUAROCKS_VERSION="3.4.0"
LUA_VERSION="5.1.5"
LIBRESSL_VERSION="3.2.2"
OPENSSL_VERSION="1.1.1h"

NGINX_RTMP_MODULE_VERSION="1.2.1"
NGINX_HTTP_FLV_MODULE_VERSION="1.2.8"
NGX_LUA_IPC_VERSION="0.1.6"
NCHAN_VERSION="1.2.7"
LUA_IO_VERSION="ed5decf2408d0546d1103e1c9246524e9cd25c2b"
LUA_VAR_NGX_VERSION="0.6"

rtmp_path="nginx-rtmp-module-${NGINX_RTMP_MODULE_VERSION}"
flv_path="nginx-http-flv-module-${NGINX_HTTP_FLV_MODULE_VERSION}"
ngx_lua_ipc_path="ngx_lua_ipc-${NGX_LUA_IPC_VERSION}"
nchan_path="nchan-${NCHAN_VERSION}"
lua_io_path="lua-io-nginx-module-${LUA_IO_VERSION}"
lua_var_ngx_path="lua-var-nginx-module-${LUA_VAR_NGX_VERSION}"
